dist: trusty
language: python
python:
  - "3.7"
services:
  - docker
env:
  - NEO4J_AUTH=none
install:
  - pip install tox
  - export PYTHONPATH=$(pwd)
  - pip install neo4j==4.0.2
before_script:
  - docker-compose -f ./tests/docker-compose.yml up -d
  - ./tests/initialize_db.py
script:
  - tox